### ISSUE TITLE
fn_format issue on broiler

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/TheThresher#5]
```
 Traceback (most recent call last):
   File "lucky.py", line 181, in <module>
     scene = Image(images[0])[hw:-hw, hw:-hw]
   File "/home/dwh2/LuckyImaging/code/data.py", line 31, in __init__
     self.fn = self.fn_format.format("%04d"%_id)
 AttributeError: 'Image' object has no attribute 'fn_format'
```

**Comment by dfm** [comment]
Should be fixed.
